stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod 777 /home/gitlab-runner/builds

build movies:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - movies
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew assemble

test movies:
  stage: test
  tags:
    - movies
  before_script:
    - chmod +x ./gradlew
  script:
    - ./gradlew check

deploy movies:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - movies
  script:
    - mkdir -p ~/api-deployment # mkdir make folder api-deployment ~/ is under current user directory so for gitlab it would be /home/gitlab/api-deployment
    - rm -rf ~/api-deployment/* # rm remove -rf is recursive files from api-deployment
    - cp -r build/libs/. ~/api-deployment # cp - copy build/libs is where
    - sudo service movies restart  # this requires sudo rights for gitlab user
