stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x gradlew

build movies:
  stage: build
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs
  tags:
    - movies
  script:
    - ./gradlew assemble

test movies:
  stage: test
  tags:
    - movies
  script:
    - ./gradlew check

deploy movies:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - movies
  script:
    - mkdir -p ~/api-deployment
    - rm -rf ~/api-deployment/*
    - cp -r build/libs/. ~/api-deployment
    - sudo service movie restart
