spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/films/filminfo
    username: host
    password: Lol12345
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true