server:
  servlet:
    context-path: /api

spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:./h2/movies;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    platform: h2
  h2:
    console:
      enabled: true
  flyway:
    user: sa
    password: sa
    url: jdbc:h2:./h2/movies
    schemas: SCHEMA1

logging:
  file:
    path: ./logs

users:
  userName: user
  userPassword: user1
  adminName: admin
  adminPassword: admin1
